[package]
name = "set1"
version = "0.1.0"
authors = ["Ram Gupta <ramgupta95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
base64 = "0.12"
lazy_static = "1.4.0"